name: On GitHub PR, Docker Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntui-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          docker build . --tag ghcr.io/$GITHUB_REPOSITORY:latest
